install:
  - git remote set-url origin https://github.com/%APPVEYOR_REPO_NAME%.git

before_build:
  - nuget restore fxcopwrapper.sln

platform: x86
configuration: Release

build:
  project: fxcopwrapper.sln

after_build:
  - nuget pack src\FxCopWrapper.nuspec -Properties version=%GitVersion_NuGetVersion%;outdir=bin\release

artifacts:
 - path: fxcopwrapper.*.nupkg
   name: NuGet
 - path: src\bin\release\FxCopWrapper*
   name: Binaries

deploy:
  - provider: NuGet
    server: https://www.nuget.org
    api_key:
      #bdhess@live.com 2015-04-13
      secure: 82b5uCCj8Hx3qWNUX4LatNKcSsmvJ+HAkyBBn5wvJUQ0CZjsN4Il4RoTTRSDcFM1
    skip_symbols: true
    artifact: NuGet
    on:
      appveyor_repo_tag: true

  - provider: GitHub
    release: v$(GitVersion_SemVer)
    auth_token:
      #fxcopwrapper-bot 2015-01-04
      secure: 3odmfMCz2wNkg3QcYAOAkigftwcjmphWJG6q8b9WTJye/RZUyeevmBIzusJRCxmv
    artifact: NuGet,Binaries
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
