install:
  - git remote set-url origin https://github.com/%APPVEYOR_REPO_NAME%.git

before_build:
  - nuget restore fxcopwrapper.sln

platform: x86
configuration: Release

build:
  project: fxcopwrapper.sln

after_build:
  - nuget pack src\FxCopWrapper.nuspec -Properties version=%GitVersion_NuGetVersion%;outdir=bin\release

artifacts:
 - path: fxcopwrapper.*.nupkg
   name: NuGet
 - path: src\bin\release\FxCopWrapper*
   name: Binaries

deploy:
  - provider: NuGet
    server: https://www.nuget.org
    api_key:
      #bdhess 2015-01-14
      secure: +o5S8m7NSWLOFM5hyIhrD+aHdZU2dLn83nCV3zIFV55OMNl5H8q2yRFsFzMMcOWn
    skip_symbols: true
    artifact: NuGet
    on:
      appveyor_repo_tag: true

  - provider: GitHub
    release: v$(GitVersion_SemVer)
    auth_token:
      #bdhess-bot 2015-04-13
      secure: xbPXf7huVM5TwkHbgC9L1vb5qe/7a5wlMqOrpArzXslYOfiUYTsjDCseoHSmPlhh
    artifact: NuGet,Binaries
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
