install:
  - git remote set-url origin https://github.com/%APPVEYOR_REPO_NAME%.git

before_build:
  - nuget restore fxcopwrapper.sln

platform: x86
configuration: Release

build:
  project: fxcopwrapper.sln

after_build:
  - nuget pack src\FxCopWrapper.nuspec -Properties version=%GitVersion_NuGetVersion%;outdir=bin\release

artifacts:
 - path: *.nupkg
   name: NuGet
 - path: src\bin\**\*.zip
   name: Binaries

deploy:
  - provider: GitHub
    release: v$(GitVersion_NuGetVersion)
    auth_token:
      #fxcopwrapper-bot 2015-01-04
      secure: 3odmfMCz2wNkg3QcYAOAkigftwcjmphWJG6q8b9WTJye/RZUyeevmBIzusJRCxmv
    artifact: NuGet,Binaries
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
