install:
  - git remote set-url origin https://github.com/%APPVEYOR_REPO_NAME%.git

before_build:
  - nuget restore fxcopwrapper.sln

platform: x86
configuration: Release

build:
  project: fxcopwrapper.sln

